[general]
import = ["~/.config/alacritty/solarized-dark.toml"]
[font]
normal = { family = "MonaspiceNe Nerd Font"}
bold = { family = "MonaspiceNe Nerd Font"}
italic = { family = "MonaspiceNe Nerd Font"}
bold_italic = { family = "MonaspiceNe Nerd Font"}
size = 15
[cursor]
style = { shape = "Beam", blinking = "On"}
vi_mode_style = { shape = "Beam", blinking = "On"}

[mouse]
hide_when_typing = true

