#!/usr/bin/env bash

# Generate and install hardware-configuration for the install process

SCRIPTPATH=$( cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
if [[ $1 != "" ]]; then
    if [[ $1 == "/" ]]; then
        echo "Dont specify / next time!"
        echo "Using / as a default option..."
        sudo nixos-generate-config
        sudo cp -v /etc/nixos/hardware-configuration.nix "$SCRIPTPATH/../system/hardware-configuration.nix"
    else
        sudo nixos-generate-config --root "$1"
        sudo cp -v /etc/nixos/hardware-configuration.nix "$SCRIPTPATH/../system/hardware-configuration.nix"
    fi
else
    echo "No root path specified"
fi
